spring:
  application:
    name: voting
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api/v1