spring:
  application:
    name: voting
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: localhost
    port: 25
    username: user
    password: user
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          transfer:
            protocol: smtp
        from: votingapp@kafara.pl

app:
  url: http://localhost:3000

server:
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      secret-key: secret-key
      expiration-time: 86400000
  max-failed-attempts: 3