spring:
  application:
    name: voting
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:/db/users.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  flyway:
    enabled: false
    baseline-on-migrate: true

  mail:
    host: localhost
    port: 25
    username: user
    password: user
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          transfer:
            protocol: smtp
        from: votingapp@kafara.pl
  thymeleaf:
    check-template-location: false


app:
  url: http://localhost:5173

server:
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      secret-key: secret-key
      expiration-time: 86400000
  max-failed-attempts: 3

sejm:
  api:
    url: https://api.sejm.gov.pl/sejm/
  term: term10