spring:
  application:
    name: voting
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      secret-key: secret-key
      expiration-time: 86400000
  max-failed-attempts: 3