services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting_app
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    networks:
      - docker-network

  spring-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/voting_app
    restart: no
    ports:
      - "8080:8080"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge