services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting_app
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data:/var/lib/postgresql/data

  smtp4dev:
    image: rnwood/smtp4dev:3.6.0
    ports:
      - "5000:80"
      - "25:25"
    restart: no